# Generated by Django 5.2.13 on 2026-04-11 17:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.DateField()),
                ('to_year', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certifications/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.DateField()),
                ('to_year', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('flyer', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('about', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='technology_logos/')),
                ('link', models.URLField(blank=True, null=True)),
                ('annotations', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(choices=[(0, 'Non Applicable'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.DateField()),
                ('to_year', models.DateField()),
                ('name', models.CharField(max_length=101)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('courses', models.ManyToManyField(related_name='schools', to='portefolio.course')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('link', models.URLField(blank=True, null=True)),
                ('schools', models.ManyToManyField(related_name='institutions', to='portefolio.school')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('applied_concepts', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('repository', models.URLField(blank=True, null=True)),
                ('technologies', models.ManyToManyField(related_name='projects', to='portefolio.technology')),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)])),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tfc_images/')),
                ('pdf', models.URLField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('courses', models.ManyToManyField(related_name='tfcs', to='portefolio.course')),
                ('supervisors', models.ManyToManyField(related_name='tfcs', to='portefolio.teacher')),
                ('technologies', models.ManyToManyField(related_name='tfcs', to='portefolio.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.IntegerField(choices=[(0, 'Non Applicable'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('projects', models.ManyToManyField(blank=True, related_name='skills', to='portefolio.project')),
                ('technologies', models.ManyToManyField(blank=True, related_name='skills', to='portefolio.technology')),
                ('tfcs', models.ManyToManyField(blank=True, related_name='skills', to='portefolio.tfc')),
            ],
        ),
        migrations.CreateModel(
            name='UC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('program', models.TextField()),
                ('objectives', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uc_images/')),
                ('courses', models.ManyToManyField(related_name='ucs', to='portefolio.course')),
                ('teachers', models.ManyToManyField(related_name='ucs', to='portefolio.teacher')),
                ('technologies', models.ManyToManyField(blank=True, related_name='ucs', to='portefolio.technology')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portefolio.uc'),
        ),
    ]
