# Generated by Django 5.2.13 on 2026-04-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='portefolio.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='portefolio.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
