# Generated by Django 5.2.13 on 2026-04-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('program', models.TextField()),
                ('objectives', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uc_images/')),
                ('courses', models.ManyToManyField(related_name='ucs', to='portefolio.course')),
            ],
        ),
    ]
