# Generated by Django 5.2.13 on 2026-04-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0002_uc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='uc',
            name='teachers',
            field=models.ManyToManyField(related_name='ucs', to='portefolio.teacher'),
        ),
    ]
