# Generated by Django 5.2.13 on 2026-04-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0002_certification_institution_workshop_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='school',
            name='courses',
        ),
        migrations.AddField(
            model_name='institution',
            name='schools',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='portefolio.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='portefolio.course'),
            preserve_default=False,
        ),
    ]
