# Generated by Django 5.2.13 on 2026-04-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0003_remove_institution_schools_remove_school_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='school',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='portefolio.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='portefolio.institution'),
            preserve_default=False,
        ),
    ]
