# Generated by Django 5.2.13 on 2026-04-11 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0004_remove_institution_schools_remove_school_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='from_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='certification',
            name='to_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='from_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='to_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='from_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='to_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
