# Generated by Django 5.2.13 on 2026-04-11 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0004_remove_institution_schools_remove_school_courses_and_more'),
    ]

    operations = [
        # CERTIFICATION
        migrations.RunSQL(
            """
            ALTER TABLE portefolio_certification
            ALTER COLUMN from_year TYPE integer
            USING EXTRACT(YEAR FROM from_year);
            """
        ),

        migrations.RunSQL(
            """
            ALTER TABLE portefolio_certification
            ALTER COLUMN to_year TYPE integer
            USING EXTRACT(YEAR FROM to_year);
            """
        ),

        # COURSE
        migrations.RunSQL(
            """
            ALTER TABLE portefolio_course
            ALTER COLUMN from_year TYPE integer
            USING EXTRACT(YEAR FROM from_year);
            """
        ),

        migrations.RunSQL(
            """
            ALTER TABLE portefolio_course
            ALTER COLUMN to_year TYPE integer
            USING EXTRACT(YEAR FROM to_year);
            """
        ),

        # WORKSHOP
        migrations.RunSQL(
            """
            ALTER TABLE portefolio_workshop
            ALTER COLUMN from_year TYPE integer
            USING EXTRACT(YEAR FROM from_year);
            """
        ),

        migrations.RunSQL(
            """
            ALTER TABLE portefolio_workshop
            ALTER COLUMN to_year TYPE integer
            USING EXTRACT(YEAR FROM to_year);
            """
        ),
    ]
