# Generated by Django 5.2.13 on 2026-04-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0005_alter_certification_from_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='portefolio.technology'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='workshops', to='portefolio.technology'),
        ),
    ]
