# Generated by Django 5.2.13 on 2026-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0006_certification_technologies_workshop_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
