# Generated by Django 5.2.13 on 2026-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0006_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='portefolio.technology'),
        ),
        migrations.AddField(
            model_name='uc',
            name='technologies',
            field=models.ManyToManyField(related_name='ucs', to='portefolio.technology'),
        ),
    ]
