# Generated by Django 5.2.13 on 2026-04-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0007_school_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
