# Generated by Django 5.2.13 on 2026-04-11 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0007_project_technologies_uc_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.IntegerField(max_length=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tfc_images/')),
                ('pdf', models.URLField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('courses', models.ManyToManyField(related_name='tfcs', to='portefolio.course')),
                ('supervisors', models.ManyToManyField(related_name='tfcs', to='portefolio.teacher')),
                ('technologies', models.ManyToManyField(related_name='tfcs', to='portefolio.technology')),
            ],
        ),
    ]
