# Generated by Django 5.2.13 on 2026-04-11 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0008_alter_tfc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='from_year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='certification',
            name='to_year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='course',
            name='from_year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='course',
            name='to_year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='from_year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='to_year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
