# Generated by Django 5.2.13 on 2026-04-11 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0008_tfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
