# Generated by Django 5.2.13 on 2026-05-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0009_alter_certification_from_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uc',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='uc',
            name='objectives',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='uc',
            name='program',
            field=models.TextField(default=' '),
        ),
    ]
