# Generated by Django 5.2.13 on 2026-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0009_alter_tfc_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='from_year',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='to_year',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='level',
            field=models.IntegerField(choices=[(0, 'Non Applicable'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
        migrations.AlterField(
            model_name='uc',
            name='technologies',
            field=models.ManyToManyField(blank=True, null=True, related_name='ucs', to='portefolio.technology'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.IntegerField(choices=[(0, 'Non Applicable'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('projects', models.ManyToManyField(blank=True, null=True, related_name='skills', to='portefolio.project')),
                ('technologies', models.ManyToManyField(blank=True, null=True, related_name='skills', to='portefolio.technology')),
                ('tfcs', models.ManyToManyField(blank=True, null=True, related_name='skills', to='portefolio.tfc')),
            ],
        ),
    ]
