# Generated by Django 5.2.13 on 2026-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0010_course_from_year_course_to_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='from_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='to_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
