# Generated by Django 5.2.13 on 2026-05-08 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0010_alter_uc_description_alter_uc_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uc',
            name='year',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uc',
            name='name',
            field=models.CharField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
