# Generated by Django 5.2.13 on 2026-04-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0011_alter_course_from_year_alter_course_to_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.DateTimeField(blank=True, null=True)),
                ('to_year', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certifications/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
