# Generated by Django 5.2.13 on 2026-04-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0013_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.DateTimeField()),
                ('to_year', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='certification',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='to_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='to_year',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='to_year',
        ),
        migrations.AlterField(
            model_name='skill',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='skills', to='portefolio.project'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='skills', to='portefolio.technology'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tfcs',
            field=models.ManyToManyField(blank=True, related_name='skills', to='portefolio.tfc'),
        ),
        migrations.AlterField(
            model_name='uc',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='ucs', to='portefolio.technology'),
        ),
        migrations.AddField(
            model_name='certification',
            name='education_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portefolio.education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='education_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portefolio.education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='education_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portefolio.education'),
            preserve_default=False,
        ),
    ]
