# Generated by Django 5.2.13 on 2026-05-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0013_uc_semester_alter_uc_name_alter_uc_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uc',
            name='courses',
        ),
        migrations.AddField(
            model_name='uc',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ucs', to='portefolio.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uc',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='ucs', to='portefolio.teacher'),
        ),
    ]
