# Generated by Django 5.2.13 on 2026-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0014_education_remove_certification_from_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='education_ptr',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='education_ptr',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='education_ptr',
        ),
        migrations.AddField(
            model_name='certification',
            name='from_year',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='certification',
            name='to_year',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='from_year',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='to_year',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='from_year',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='to_year',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
