# Generated by Django 5.2.13 on 2026-05-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0014_remove_uc_courses_uc_course_alter_uc_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
