# Generated by Django 6.0.5 on 2026-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portefolio", "0015_teacher_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
