# Generated by Django 5.2.13 on 2026-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0015_remove_course_education_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='from_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='to_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='from_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='to_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='from_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='to_year',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('courses', models.ManyToManyField(related_name='schools', to='portefolio.course')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('link', models.URLField(blank=True, null=True)),
                ('schools', models.ManyToManyField(related_name='institutions', to='portefolio.school')),
            ],
        ),
    ]
